config/routes.rb
XwingRank::Application.routes.draw do
  
  resources :rankings

  get 'faq' => 'public_tourney#faq'

  devise_for :users
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tourneys do
    get 'report' => 'tourneys#report'
    get 'dropPlayer/:player_id' => 'rounds#dropPlayer'
    get 'undropPlayer/:player_id' => 'rounds#undropPlayer'
    get 'removePlayer/:player_id' => 'rounds#removePlayer'
    get 'newPlayer/' => 'rounds#newPlayer'
    get 'printInscribed/' => 'tourneys#printInscribed'
    get 'printRanking/' => 'tourneys#printRanking'
    post 'createInscription/' => 'rounds#createInscription'
    post 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'elimination/' => 'tourneys#elimination'
    post 'startElimination/' => 'tourneys#startElimination'
    resources :rounds do
      get 'seedRound/' => 'rounds#seedRound'
      get 'printRound/' => 'rounds#printRound'
      resources :matches
    end
  end

  resources :players

  root 'players#list'

  get 'simple' => 'players#simple'

  get 'tourney/:publicId' => 'public_tourney#index'

end

app/models/tourney.rb
class Tourney < ActiveRecord::Base
  
  SWISS_MODE = 1
  ELIMINATION_MODE = 2
  
	has_many :rounds, :dependent => :delete_all
  has_and_belongs_to_many :players
  belongs_to :user
  has_many :rankings, :dependent => :delete_all
  has_many :matches, through: :rounds
  
  validates :titulo, presence: true
  validates :titulo, length: {minimum: 8} 
  validates :seedType, presence: true
  validates :seedType, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 2 }
  
  before_create :initPublicId
  
  def self.states
    [I18n.t('new'), I18n.t('published'), I18n.t('initiated'), I18n.t('finished')]
  end
  
  def stateName
    Tourney.states[self.state]
  end
  
  def lastRound
    self.rounds.last
  end  
  
  def ranking
    data=Result.joins(match: [round: [:tourney]] ).includes(:player).where(tourneys: {id: self.id}).select('results.player_id').group('results.player_id').sum(:score)
  end
  
  def addPlayerToRanking(player,bye)
    ranking = Ranking.new
    ranking.player = player
    ranking.tourney = self
    ranking.bye = bye
    ranking.save
  end
  
  def removePlayerFromRanking(player)
    ranking = Ranking.find_by(tourney_id: self.id, player_id: player.id)
    ranking.destroy
  end
  
  def calculateSOS
    self.rankings.each {|ranking| 
      ranking.sos = calculateSOSFor(ranking.player)
      ranking.save
    }
  end

  def calculateSOSFor(player)
    playerMatches = self.matches.where(:player1 => player)
    sos = 0
    playerMatches.each {|match| 
      unless match.player2.nil?
        ranking = self.rankings.find_by(player_id: match.player2)
        sos += ranking.points
      end
    }
    
    playerMatches = self.matches.where(:player2 => player)
    playerMatches.each {|match| 
      unless match.player1.nil?
        ranking = self.rankings.find_by(player_id: match.player1)
        sos += ranking.points
      end
    }
    return sos
  end
  
  
  def startEliminationRounds(numberOfPlayers)
    return if self.mode == ELIMINATION_MODE # Tourney already in Elimination mode
    
    self.mode = ELIMINATION_MODE
    self.save
    
    self.rankings.each { |ranking|
      ranking.eliminated = true
      ranking.save
    }
    
    i = 0
    while i < numberOfPlayers
      self.rankings[i].eliminated = false
      self.rankings[i].save
      i += 1
    end
  end
  
  def isSwissModeActivated
    return self.mode == SWISS_MODE
  end
  
private 
  def initPublicId
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map { |i| i.to_a }.flatten
    self.publicId = (0...10).map { o[rand(o.length)] }.join
  end  
end

app/controllers/tourneys_controller.rb
class TourneysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tourney, only: [:show, :edit, :update, :destroy]
  
  # GET /tourneys
  # GET /tourneys.json
  def index
    @tourneys = current_user.tourneys.order('playDate desc')
  end

  # GET /tourneys/1
  # GET /tourneys/1.json
  def show
  end

  # GET /tourneys/new
  def new
    @tourney = current_user.tourneys.new
  end

  # GET /tourneys/1/edit
  def edit
  end

  # POST /tourneys
  # POST /tourneys.json
  def create
    @tourney = current_user.tourneys.new(tourney_params)

    respond_to do |format|
      if @tourney.save
        format.html { redirect_to tourneys_url, notice: t('tourneyCreated') }
        format.json { render action: 'show', status: :created, location: @tourney }
      else
        format.html { render action: 'new' }
        format.json { render json: @tourney.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tourneys/1
  # PATCH/PUT /tourneys/1.json
  def update
    respond_to do |format|
      if @tourney.update(tourney_params)
        format.html { redirect_to tourney_rounds_url(@tourney), notice: t('tourneyUpdated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tourney.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tourneys/1
  # DELETE /tourneys/1.json
  def destroy
    @tourney.destroy
    respond_to do |format|
      format.html { redirect_to tourneys_url }
      format.json { head :no_content }
    end
  end
  
  def report
    @tourney = current_user.tourneys.find(params[:tourney_id])
    render layout: false
    filename = @tourney.titulo.camelize + ".txt"
    headers['Pragma'] = 'public'
    headers["Content-type"] = "text/plain" 
    headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
    headers['Content-Disposition'] = "attachment; filename=\"#{filename}\"" 
    headers['Expires'] = "0" 
  end
  
  def printInscribed
    @tourney = current_user.tourneys.find(params[:tourney_id])
    render :layout => 'printable'
  end
  
  def printRanking
    @tourney = current_user.tourneys.find(params[:tourney_id])
    render :layout => 'printable'
  end
  
  def elimination
    @tourney = current_user.tourneys.find(params[:tourney_id])
  end
  
  def startElimination
    @tourney = current_user.tourneys.find(params[:tourney_id])
    
    # check last round is filled completely
    @lastRound = @tourney.lastRound
    if !@lastRound.nil? and !@lastRound.allMatchesFilled?
      respond_to do |format|
        format.html { redirect_to :back, alert: t('lastRoundNotFinished') }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
      return
    end
    
    respond_to do |format|
      if params[:numberOfPlayersForTop].nil? or params[:numberOfPlayersForTop] == "" or params[:numberOfPlayersForTop].to_i <= 0
        format.html { redirect_to tourney_elimination_url(@tourney), alert: t('numberOfPlayersNeeded') }
      else
        numberOfPlayers = params[:numberOfPlayersForTop].to_i
        @tourney.startEliminationRounds(numberOfPlayers)
         # Create new round
        format.html { redirect_to tourney_createAndSeedRound_url(@tourney), notice: t('tourneyUpdated') }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tourney
      @tourney = current_user.tourneys.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tourney_params
      params.require(:tourney).permit(:state, :titulo, :playDate, :publicId, :seedType)
    end
end

app/helpers/tourneys_helper.rb
module TourneysHelper
  
  def collectTournamentStates
    i = -1;
    Tourney.states.collect {|p| [ p, i += 1 ] }
  end
  
  
  def checkActiveTab(tabName)
    if @activeTab == tabName
      return "active"
    end
    return ""
  end

  def checkRound(round)
    if @selectedRound == round
      return "active"
    end
    return ""
  end
  
  def playerNameDrop(ranking)
    s = ""
    s += '<s>' if ranking.dropped
    s += ranking.player.completeName
    s += '</s>' if ranking.dropped
    return s
  end
end

app/views/tourneys/_form.html.erb
<%= form_for(@tourney, role: "form") do |f| %>
  <% if @tourney.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tourney.errors.count, "error") %> prohibited this tourney from being saved:</h2>

      <ul>
      <% @tourney.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :state %><br>
	<%= select("tourney", "state", collectTournamentStates(), class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :playDate %><br>
	<%= date_select :tourney, :playDate %>
  </div>
  <div class="form-group">
    <%= f.label :publicId %><br>
	<%= f.text_field :publicId, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/tourneys/_info.html.erb
<h2>
  <%= link_to @tourney.titulo, tourney_rounds_path(@tourney) %>
</h2>

app/views/tourneys/_inscribed.html.erb
<%= link_to t('newInscription'), "/tourneys/#{@tourney.id}/newPlayer", class: "btn btn-primary btn-lg pull-right", role:"button" %>

<%= render partial: 'rounds/notice' %>
<h2><%= t('listingInscribedPlayers')%></h2>

<%= link_to t('printPage'), "/tourneys/#{@tourney.id}/printInscribed", class: "btn btn-info btn-lg pull-left", role:"button", :target => "_blank" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Ranking.human_attribute_name(:player_id) %></th>
	  	<th><%= Ranking.human_attribute_name(:bye) %></th>
      <th></th>
			<th></th>
    </tr>
  </thead>

  <tbody>
    <% @tourney.rankings.each do |ranking| %>
      <tr>
				<% if ranking.dropped %>
				<td><s><%= ranking.player.completeName %></s></td>
				<% else %>
        <td><%= ranking.player.completeName %></td>
				<% end %>
		<td><%= ranking.bye if ranking.bye == true %></td>
		<% if ranking.dropped %>
		<td><%= link_to I18n.t('undrop'), "/tourneys/#{@tourney.id}/undropPlayer/#{ranking.player.id}", class: "btn btn-warning btn-xs", role:"button" %></td>
		<% else %>
    <td><%= link_to I18n.t('drop'), "/tourneys/#{@tourney.id}/dropPlayer/#{ranking.player.id}", class: "btn btn-warning btn-xs", role:"button" %></td>
		<% end %>
        <td><%= link_to I18n.t('destroy'), "/tourneys/#{@tourney.id}/removePlayer/#{ranking.player.id}",  data: { confirm: t("areYouSure") }, class: "btn btn-danger btn-xs", role:"button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('newInscription'), "/tourneys/#{@tourney.id}/newPlayer", class: "btn btn-primary btn-lg pull-right", role:"button" %>

app/views/tourneys/_ranking.html.erb
<%= render partial: 'rounds/notice' %>
<% position = 0 %>
<h2><%= t('ranking')%></h2>
<%= link_to t('printPage'), "/tourneys/#{@tourney.id}/printRanking", class: "btn btn-info btn-lg pull-left", role:"button", :target => "_blank" %>
<table class="table">
  <thead>
    <tr>
	  <th><%= t('position')%></th>
      <th><%= Player.human_attribute_name(:player_id) %></th>
			<th><%= Ranking.human_attribute_name(:numberOfMatches) %></th>
      <th><%= Ranking.human_attribute_name(:points) %></th>
	  <th><%= Ranking.human_attribute_name(:breakpoints) %></th>
	  <th><%= Ranking.human_attribute_name(:sos) %></th>
    </tr>
  </thead>

  <tbody>
    <% @tourney.rankings.each do |ranking| %>
      <tr>
		<td><%= position += 1%>  
    <td><%= ranking.player.completeName %></td>
		<td><%= ranking.numberOfMatches %></td>
		<td><%= ranking.points %></td>
		<td><%= ranking.breakpoints %></td>
		<td><%= ranking.sos %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tourneys/_rounds.html.erb
<%= render partial: 'rounds/notice' %>
<div class="row">
  <div class="col-md-2">		
		<ul class="nav nav-pills nav-stacked">
		    <% @tourney.rounds.each do |round| %>
		        <li class="<%= checkRound(round)%>"><%= link_to I18n.t('round') + " " + round.order.to_s, tourney_round_matches_path(@tourney, round) %></li>
		    <% end %>
				<li><%= link_to t('newRound'), tourney_createAndSeedRound_path(@tourney), method: :post %></li>
				<li>
					<% if @tourney.mode == 1 %>
						<%= link_to I18n.t('startElimination'), tourney_elimination_path(@tourney) %>
					<% end %>
					<% if @tourney.mode == 2 %>
						<%= I18n.t(:modeEliminationActivated) %>
					<% end %>
				</li>
				
		</ul>
  </div>
  <div class="col-md-10">
		<%= render partial: 'matches/index' %>
  </div>
</div>

app/views/tourneys/edit.html.erb
<h1><%= t('editingTourney')%></h1>

<%= render 'form' %>

app/views/tourneys/elimination.html.erb
<div class='tourney-tab'>
	<h1><%= t('tourney')%></h1>
	<%= render 'tourneys/info' %>	
</div>
<%= render partial: 'rounds/notice' %>
<div class="tab-content">
	<%= form_tag({controller: :tourneys, action: :startElimination}, method: :post) do %>
	  <div class="form-group">
	    <%= label_tag I18n.t(:numberOfPlayersForTop) %><br>
		<%= text_field_tag :numberOfPlayersForTop, nil, class: "form-control" %>
	  </div>
	  <%= submit_tag nil, class: "btn btn-default" %>
	<% end %>
</div>

app/views/tourneys/index.html.erb
<h1><%= t('listingTourneys')%></h1>
<%= link_to I18n.t('newTourney'), new_tourney_path, class: "btn btn-primary btn-lg pull-right", role:"button" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Tourney.human_attribute_name(:state) %></th>
      <th><%= Tourney.human_attribute_name(:titulo) %></th>
	  	<th><%= Tourney.human_attribute_name(:playDate) %></th>
      <th></th>
      <th></th>
			<th></th>
    </tr>
  </thead>

  <tbody>
    <% @tourneys.each do |tourney| %>
      <tr>
        <td><%= tourney.stateName %></td>
        <td><%= tourney.titulo %></td>
				
		<td><%= tourney.playDate.to_formatted_s(:long_ordinal) unless tourney.playDate.nil? %></td>
		
		<td><%= link_to I18n.t('show'), tourney_rounds_path(tourney), class: "btn btn-default btn-xs", role:"button" %></td>
        <td><%= link_to I18n.t('destroy'), tourney, method: :delete, data: { :confirm => t("areYouSure") }, class: "btn btn-danger btn-xs", role:"button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('newTourney'), new_tourney_path, class: "btn btn-primary btn-lg pull-right", role:"button" %>

app/views/tourneys/new.html.erb
<h1><%= t('newTourney')%></h1>

<%= render 'form' %>

app/views/tourneys/printInscribed.html.erb
<h2><%= t('inscribed')%></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Ranking.human_attribute_name(:player_id) %></th>
	  	<th><%= Ranking.human_attribute_name(:bye) %></th>
      <th></th>
			<th></th>
    </tr>
  </thead>

  <tbody>
    <% @tourney.rankings.each do |ranking| %>
      <tr>
				<% if ranking.dropped %>
				<td><s><%= ranking.player.completeName %></s></td>
				<% else %>
        <td><%= ranking.player.completeName %></td>
				<% end %>
		<td><%= ranking.bye if ranking.bye == true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tourneys/printRanking.html.erb
<% position = 0 %>
<h2><%= t('ranking')%></h2>
<table class="table table-striped">
  <thead>
    <tr>
	  <th><%= t('position')%></th>
      <th><%= Player.human_attribute_name(:player_id) %></th>
      <th><%= Ranking.human_attribute_name(:points) %></th>
	  <th><%= Ranking.human_attribute_name(:breakpoints) %></th>
	  <th><%= Ranking.human_attribute_name(:sos) %></th>
    </tr>
  </thead>

  <tbody>
    <% @tourney.rankings.each do |ranking| %>
      <tr>
		<td><%= position += 1%>  
		<td><%= ranking.player.completeName %></td>
		<td><%= ranking.points %></td>
		<td><%= ranking.breakpoints %></td>
		<td><%= ranking.sos %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tourneys/report.html.erb
--- PLAYERS
<% @tourney.players.each do |player| 
firstName = player.firstName || "" 
lastName = player.lastName || "" 
city = player.city || "" 
active = 'active'
ranking = Ranking.find_by(player_id: player, tourney_id: @tourney)
active = 'dropped' if ranking.dropped
%><%= "" + firstName + "\t" + lastName + "\t" + city + "\t\t0\t" + active %>
<% end %>

<% @tourney.rounds.each do |round| %>
<%= "--- ROUND " + round.order.to_s %>
	<% round.matches.each do |match| 
		firstName1 = ""
		lastName1 = ""
		firstName2 = ""
		lastName2 = ""
		firstName1 = match.player1.firstName || "" unless match.player1.nil?
		lastName1 = match.player1.lastName || "" unless match.player1.nil?
		firstName2 = match.player2.firstName || "" unless match.player2.nil?
		lastName2 = match.player2.lastName || "" unless match.player2.nil?
	%>
<%= "" + firstName1 + "\t" + lastName1 + "\t" + match.points1.to_s %><%= "\n" + firstName2 + "\t" + lastName2 + "\t" + match.points2.to_s unless match.player2.nil? %>
-
	<% end %>

<% end %>

app/views/tourneys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Tourney.human_attribute_name(:state) %>:</strong>
  <%= @tourney.state %>
</p>

<p>
  <strong><%= Tourney.human_attribute_name(:titulo) %>:</strong>
  <%= @tourney.titulo %>
</p>

<%= link_to I18n.t('edit'), edit_tourney_path(@tourney) %> |
<%= link_to 'New round', new_tourney_round_path(@tourney) %> |
<%= link_to I18n.t('back'), tourneys_path %>