config/routes.rb
XwingRank::Application.routes.draw do
  
  resources :rankings

  get 'faq' => 'public_tourney#faq'

  devise_for :users
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tourneys do
    get 'report' => 'tourneys#report'
    get 'dropPlayer/:player_id' => 'rounds#dropPlayer'
    get 'undropPlayer/:player_id' => 'rounds#undropPlayer'
    get 'removePlayer/:player_id' => 'rounds#removePlayer'
    get 'newPlayer/' => 'rounds#newPlayer'
    get 'printInscribed/' => 'tourneys#printInscribed'
    get 'printRanking/' => 'tourneys#printRanking'
    post 'createInscription/' => 'rounds#createInscription'
    post 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'elimination/' => 'tourneys#elimination'
    post 'startElimination/' => 'tourneys#startElimination'
    resources :rounds do
      get 'seedRound/' => 'rounds#seedRound'
      get 'printRound/' => 'rounds#printRound'
      resources :matches
    end
  end

  resources :players

  root 'players#list'

  get 'simple' => 'players#simple'

  get 'tourney/:publicId' => 'public_tourney#index'

end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :tourney
	has_many :matches, :dependent => :destroy
  
  validates :order, presence: true
  validate :orderValue
  
  before_validation :setCorrectOrder
  
  after_destroy :recalculateSOS
  
  default_scope { order('2 ASC') }
  
  def isFirstRound?
    self.order == 1
  end
  
  def previousRound
    Round.find_by(order: self.order - 1)
  end
  
  def recalculateSOS
    self.tourney.calculateSOS
  end
  
  def allMatchesFilled?
    self.matches.each { |match| 
      if !match.player1.nil? and match.points1.nil?
        return false
      end
      if !match.player2.nil? and match.points2.nil?
        return false
      end
    }
    return true
  end
  
  def seedRound
    if self.isFirstRound?
      self.seedFirstRound
    else
      self.tourney.calculateSOS
      self.seedNormalRound
    end
  end


  def seedFirstRound
    # Create pairings using random method
    players = self.tourney.players
    players = players.map.to_a
    

    
    # First assign a match to each player with a bye
    for index in 0..self.tourney.rankings.count-1
      ranking = self.tourney.rankings[index]
      if ranking.bye
        match = Match.new
        match.player1 = ranking.player  
        match.points1 = 100
        match.points2 = 0
        match.round = self
        match.save
        players.delete(ranking.player)
      end
      
      # Remove dropped players
      if ranking.dropped
        players.delete(ranking.player)
      end
    end
    
    while players.count > 0
      index = rand(players.count)
      player1 = players.delete_at(index)
      match = Match.new
      match.player1 = player1
      if (players.count == 0)
        match.player2 = nil
      else
        index = rand(players.count)
        player2 = players.delete_at(index)
        match.player2 = player2
      end
      checkBye(match)
      match.round = self
      match.save
    end
  end
  
  def checkBye(match)
    if !match.player1.nil? and match.player2.nil?
      match.points1 = 50
    end
  end
  
  def seedNormalRound
    if self.tourney.isSwissModeActivated
      seedSwissNormalRound
    else
      seedEliminationNormalRound
    end
  end
  
  def seedSwissNormalRound
    # Create pairings using one by one method
    players = self.tourney.rankings.map(&:player).to_a
    
    for index in 0..self.tourney.rankings.count-1
      ranking = self.tourney.rankings[index]      
      # Remove dropped players
      if ranking.dropped
        players.delete(ranking.player)
      end
    end
    
    until players.empty?
      player1 = players.shift
      player2 = players.shift
      tempPlayers = []
      while checkRepeated(player1,player2) and !players.empty?
        # Put other player2
        tempPlayers << player2
        player2 = players.shift
      end
      if tempPlayers.count != 0 
        players = tempPlayers + players
      end
      match = Match.new
      match.player1 = player1
      match.player2 = player2
      match.round = self
      match.save
    end
  end
  
  def seedEliminationNormalRound
    # Create pairings using one by one method
    players = self.tourney.rankings.map(&:player).to_a

    for index in 0..self.tourney.rankings.count-1
      ranking = self.tourney.rankings[index]
      # Remove dropped players
      if ranking.dropped
        players.delete(ranking.player)
      end
      
      # Remove eliminated players
      if ranking.eliminated
        players.delete(ranking.player)
      end
    end

    # Emparejar primero con ultimo y repetir
    until players.empty?
      player1 = players.shift
      player2 = players.pop
      match = Match.new
      match.player1 = player1
      match.player2 = player2
      match.round = self
      checkBye(match)
      match.save
    end
  end

  def seedGroupedRound
    players = self.tourney.rankings.map(&:player).to_a
    groups = []
    
    # Make ordered groups grouping by match points
    until players.empty?
      player = players.shift
      group = [player]
      while !players.empty? and player.points == players[0].points
        group << players.shift
      end
      groups << group
    end
    
    until groups.empty?
      group = groups.shift
      oddPlayer = nil
      if gorup.length.odd?
        oddPlayer = group.pop
      end
      until group.empty?
        player1 = players.shift
        player2 = players.pop
        tempPlayers = []
        while checkRepeated(player1,player2) and !players.empty?
          # Put other player2
          tempPlayers.unshift(player2)
          player2 = players.pop
        end
        
        
      end
    end
  end  

  def checkRepeated(player1,player2)
    match = self.tourney.matches.find_by(player1_id: player1, player2_id: player2)
    return true unless match.nil?
    match = self.tourney.matches.find_by(player1_id: player2, player2_id: player1)
    return true unless match.nil?
    
    return false
  end
  
private
  def orderValue
    if !self.order.nil? and self.order <= 0
      errors.add(:points1, I18n.t('orderPositive'))
    end
  end
  
  def setCorrectOrder
    if self.tourney.rounds.count == 0
      self.order = 1
    else
      lastRound = self.tourney.rounds.maximum(:order)
      self.order = lastRound + 1
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_parent
  before_action :set_round, only: [:show, :edit, :update, :destroy]
  
  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = @tourney.rounds
    @rankings =  @tourney.rankings
    @selectedRound = @tourney.lastRound
    @matches = @selectedRound.matches unless @selectedRound.nil?
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    # @round = Round.find(params[:round])
  end

  # GET /rounds/new
  def new
    setActiveTab(:rounds)
    @round = @tourney.rounds.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    setActiveTab(:rounds)
    @round = @tourney.rounds.new
    
    respond_to do |format|
      if @round.save
        format.html { redirect_to [@tourney, @round], notice: t('roundCreated') }
        format.json { render action: 'show', status: :created, location: @round }
      else
        format.html { render action: 'new' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    setActiveTab(:rounds)
    @round = @tourney.rounds.find(params[:id])

    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to [@tourney, @round], notice: t('roundUpdated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    setActiveTab(:rounds)
    @round = @tourney.rounds.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to tourney_rounds_path(@tourney) }
      format.json { head :no_content }
    end
  end
  
  #GET 
  def removePlayer
    setActiveTab(:inscribed)
    unless @tourney.lastRound.nil?
      respond_to do |format|
        format.html { redirect_to tourney_rounds_path(@tourney), alert: t('playerCantBeRemoved') }
        format.json { head :no_content }
      end
      return
    end
    @tourney.players.delete(params[:player_id])
    player = Player.find(params[:player_id])
    @tourney.removePlayerFromRanking(player)
    
    respond_to do |format|
      format.html { redirect_to tourney_rounds_path(@tourney), notice: t('playerRemoved') }
      format.json { head :no_content }
    end
  end

  def dropPlayer
    setActiveTab(:inscribed)
    ranking = Ranking.find_by(player_id: params[:player_id], tourney_id: @tourney)
    
    ranking.dropped = true unless ranking.nil?
    ranking.save
    respond_to do |format|
      format.html { redirect_to tourney_rounds_path(@tourney), notice: t('playerDropped') }
      format.json { head :no_content }
    end
  end
  
  def undropPlayer
    setActiveTab(:inscribed)
    ranking = Ranking.find_by(player_id: params[:player_id], tourney_id: @tourney)
    
    ranking.dropped = false unless ranking.nil?
    ranking.save
    respond_to do |format|
      format.html { redirect_to tourney_rounds_path(@tourney), notice: t('playerUndropped') }
      format.json { head :no_content }
    end
  end
  
  def newPlayer
    if params[:player_id].nil? or params[:player_id] == ""
      @player = @tourney.players.new
    else
      @player = Player.find(params[:player_id])
    end
  end
  
  def createInscription
    setActiveTab(:inscribed)
    inscribedplayerexists = @tourney.players.exists?(id: params[:player][:id])
    
    if !inscribedplayerexists
      player = Player.find(params[:player][:id])
      @tourney.players << player
  
      @tourney.addPlayerToRanking(player,params[:inscription][:bye])
    end
    
    respond_to do |format|
      if !inscribedplayerexists
        if @tourney.save
          format.html { redirect_to tourney_rounds_path(@tourney), notice: t('playerInscribed') }
          format.json { render action: I18n.t('show'), status: :created, location: @tourney }
        else
          format.html { render action: 'newPlayer' }
          format.json { render json: @round.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to tourney_rounds_path(@tourney), alert: t('playerAlreadyInscribed') }
      end
    end
  end
  
  def seedRound
    setActiveTab(:rounds)
    @round = @tourney.rounds.find(params[:round_id])
    @round.seedRound
    
    respond_to do |format|
      format.html { redirect_to [@tourney, @round], notice: t('roundUpdated') }
      format.json { head :no_content }
    end
  end
  
  def printRound
    setActiveTab(:rounds)
    @round = @tourney.rounds.find(params[:round_id])
    @matches = @round.matches
    @selectedRound = @round
    render :layout => 'printable'
  end
  
  def createAndSeedRound
    setActiveTab(:rounds)
    # check last round is filled completely
    @lastRound = @tourney.lastRound
    if !@lastRound.nil? and !@lastRound.allMatchesFilled?
      respond_to do |format|
        format.html { redirect_to :back, alert: t('lastRoundNotFinished') }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
      return
    end
    
    @round = @tourney.rounds.new
    
    respond_to do |format|
      if !@round.save
        format.html { render action: 'new' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      else
        @round.seedRound
        format.html { redirect_to tourney_rounds_path(@tourney), notice: t('roundCreated') }
        format.json { head :no_content }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = @tourney.rounds.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:order, :tourney_id, :player)
    end

    
    def load_parent
      @tourney = current_user.tourneys.find(params[:tourney_id]) 
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  def collectPlayersForAllTournmanets
    Player.all.order("firstName ASC, lastName ASC").collect {|p| [ p.completeName, p.id ] }
  end
end

app/views/rounds/_form.html.erb
<%= form_for([@tourney, @round], role: "form") do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_group">
    <%= f.label :order %><br>
    <%= f.number_field :order, class: "form-control" %>
  </div>
  <div class="form_group">
    <%= f.label :tourney_id %><br>
    <%= f.number_field :tourney_id, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/rounds/_notice.html.erb
		<% if !notice.nil? %>
			  <div class="alert alert-info"><%= notice %></div>
		<% end %>
		<% if !alert.nil? %>
			  <div class="alert alert-danger"><%= alert %></div>
		<% end %>

app/views/rounds/edit.html.erb
<h1><%= t('editingRound')%></h1>

<%= render 'form' %>

<%= link_to I18n.t('back'), tourney_rounds_path(@tourney) %>

app/views/rounds/index.html.erb
<div class='tourney-tab'>
	<ul class="nav nav-pills nav-stacked pull-right">
		<li>
			<%= link_to I18n.t('editTourney'), edit_tourney_path(@tourney)%>
		</li>
	    <% unless @tourney.publicId.nil? %>
		<li>
		  <% url = url_for(:controller => 'public_tourney', :action => 'index', :publicId => @tourney.publicId) %>
	      <%= link_to I18n.t('publicURL'), url, target: "_blank" %>
	    <% end %>
		<li>
			<%= link_to I18n.t('report'), tourney_report_path(@tourney) %>
		</li>		
	</ul>
	<h1><%= t('tourney')%></h1>
	<%= render 'tourneys/info' %>	
	
</div>
<ul class="nav nav-tabs tourney-tabs" role="tablist">
  <li class="<%= checkActiveTab(:inscribed)%>" ><a href="#tab1" role="tab" data-toggle="tab"><%= t('inscribed')%></a></li>
  <li class="<%= checkActiveTab(:ranking)%>"><a href="#tab2" role="tab" data-toggle="tab"><%= t('ranking')%></a></li>
  <li class="<%= checkActiveTab(:rounds)%>"><a href="#tab3" role="tab" data-toggle="tab"><%= t('rounds')%></a></li>
</ul>



<div class="tab-content">
	<div class="tab-pane <%= checkActiveTab(:inscribed)%>" id="tab1"><%= render 'tourneys/inscribed' %></div>
	<div class="tab-pane <%= checkActiveTab(:ranking)%>" id="tab2"><%= render 'tourneys/ranking' %></div>
	<div class="tab-pane <%= checkActiveTab(:rounds)%>" id="tab3"><%= render 'tourneys/rounds' %></div>
</div>

app/views/rounds/new.html.erb
<h1><%= t('newRound')%></h1>

<%= render 'form' %>

<%= link_to I18n.t('back'), tourney_rounds_path(@tourney) %>

app/views/rounds/newPlayer.html.erb
<%= link_to t('newPlayer'), new_player_path(tourney_id: @tourney), class: "btn btn-primary btn-lg pull-right", role:"button" %>

<%= render 'tourneys/info' %>

<h1><%= t('newInscription')%></h1>

<%= form_for("inscription", url: "/tourneys/#{@tourney.id}/createInscription", role: "form") do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= Player.human_attribute_name(:firstName) %><br>
	<%= select("player", "id", collectPlayersForAllTournmanets, {include_blank: 'None'}, class: "form-control") %>
  </div>  
  
  <div class="form-group">
	  <%= f.label :bye %><br>
	  <%= f.check_box :bye %>
  </div>  
  
  <%= f.submit class: "btn btn-default" %>
<% end %>
<%= link_to t('newPlayer'), new_player_path(tourney_id: @tourney), class: "btn btn-primary btn-lg pull-right", role:"button" %>

app/views/rounds/printRound.html.erb
<% i = 0 %>
<h1><%= t('listingMatches') %> - <%= t('round') + " " + @selectedRound.order.to_s unless @selectedRound.nil? %></h1>

<table class="table table-striped">
  <thead>
    <tr>
	  <th><%= I18n.t('table') %></th>
      <th><%= Match.human_attribute_name(:player1_id) %></th>
      <th><%= Match.human_attribute_name(:points1) %></th>
      <th><%= Match.human_attribute_name(:player2_id) %></th>
      <th><%= Match.human_attribute_name(:points2) %></th>
    </tr>
  </thead>

  <tbody>
		<% @matches ||= [] %>
    <% @matches.each do |match| %>
      <tr>
		<td><%= i+= 1 %></td>
        <td><%= match.player1.completeName %></td>
        <td><%= match.points1 %></td>
        <td><%= match.player2.completeName unless match.player2.nil? %></td>
        <td><%= match.points2 unless match.player2.nil? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Round.human_attribute_name(:order) %>:</strong>
  <%= @round.order %>
</p>

<p>
  <strong><%= Round.human_attribute_name(:tourney_id) %>:</strong>
  <%= @round.tourney_id %>
</p>

<%= link_to I18n.t('edit'), edit_tourney_round_path(@tourney,@round) %> |
<%= link_to I18n.t('back'), tourney_rounds_path(@tourney) %>