config/routes.rb
XwingRank::Application.routes.draw do
  
  resources :rankings

  get 'faq' => 'public_tourney#faq'

  devise_for :users
  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tourneys do
    get 'report' => 'tourneys#report'
    get 'dropPlayer/:player_id' => 'rounds#dropPlayer'
    get 'undropPlayer/:player_id' => 'rounds#undropPlayer'
    get 'removePlayer/:player_id' => 'rounds#removePlayer'
    get 'newPlayer/' => 'rounds#newPlayer'
    get 'printInscribed/' => 'tourneys#printInscribed'
    get 'printRanking/' => 'tourneys#printRanking'
    post 'createInscription/' => 'rounds#createInscription'
    post 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'createAndSeedRound/' => 'rounds#createAndSeedRound'
    get 'elimination/' => 'tourneys#elimination'
    post 'startElimination/' => 'tourneys#startElimination'
    resources :rounds do
      get 'seedRound/' => 'rounds#seedRound'
      get 'printRound/' => 'rounds#printRound'
      resources :matches
    end
  end

  resources :players

  root 'players#list'

  get 'simple' => 'players#simple'

  get 'tourney/:publicId' => 'public_tourney#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :round
  belongs_to :player1, :class_name => :Player
  belongs_to :player2, :class_name => :Player 

  after_create :addRankings
  before_update :removeRankings
  after_update :addRankings
  before_destroy :removeRankings

  validate :pointsValues
  validate :playersAreDifferent
  validates :player1, presence: true
  # player2 == nil means that player1 receives a bye

  after_save :update_rankings

  def self.possibleResults
    [0,1,3,5]
  end
  
  private
    def update_rankings
      return if self.points1.nil?
      return if self.points2.nil?
      return if self.player1.nil?
      return if self.player2.nil?
      
      winProb1 = EloHelper.calculateWinProb(self.player1.ranking, self.player2.ranking)
      winProb2 = EloHelper.calculateWinProb(self.player2.ranking, self.player1.ranking)
    	win1 = 0.5
      win2 = 0.5
    	win1 = 1 if self.points1 > self.points2
    	win1 = 0 if self.points2 > self.points1
    	win2 = 0 if win1 == 1
    	win2 = 1 if win1 == 0
    	self.player1.ranking = EloHelper.calculateNewRanking(self.player1.ranking, winProb1, win1)
    	self.player2.ranking = EloHelper.calculateNewRanking(self.player2.ranking, winProb2, win2)
    	self.player1.save
    	self.player2.save
    end
    
    def addRankings
      return if self.points1.nil?
      self.points2 = 0 if self.points2.nil?
      
      addRankingForPlayer(self.player1,self.points1,self.points2,self.player2) 
      addRankingForPlayer(self.player2,self.points2,self.points1,self.player1) unless self.player2.nil?
    end
    
    def addRankingForPlayer(player,playerPoints, opponentPoints,opponent)
      difference,breakpoints,winner,modifiedWin,draw = calculateResults(player,playerPoints, opponentPoints,opponent)      
      
      earned = pointsEarned(winner,modifiedWin,draw)
      ranking = Ranking.find_by(player_id: player.id, tourney_id: self.round.tourney.id)
      ranking.breakpoints += breakpoints
      ranking.points += earned
      ranking.numberOfMatches += 1
      ranking.save    
    end
    
    def pointsEarned(winner,modifiedWin,draw)
      return 1 if draw
      return 0 unless winner
      return 3 if modifiedWin
      return 5
    end

    def removeRankings
      
      prevMatch = Match.find(self.id)
      return if prevMatch.points1.nil?
      prevMatch.points2 = 0 if prevMatch.points2.nil?
      
      removeRankingForPlayer(prevMatch.player1,prevMatch.points1,prevMatch.points2,prevMatch.player2)
      removeRankingForPlayer(prevMatch.player2,prevMatch.points2,prevMatch.points1,prevMatch.player1) unless prevMatch.player2.nil?
    end
    
    def removeRankingForPlayer(player,playerPoints, opponentPoints,opponent)
      difference,breakpoints,winner,modifiedWin,draw = calculateResults(player,playerPoints, opponentPoints,opponent)
      
      earned = pointsEarned(winner,modifiedWin,draw)
      ranking = Ranking.find_by(player_id: player.id, tourney_id: self.round.tourney.id)
      ranking.breakpoints -= breakpoints
      ranking.points -= earned
      ranking.numberOfMatches -= 1
      ranking.save
    end
    
    def calculateResults(player,playerPoints, opponentPoints,opponent)
      difference = playerPoints - opponentPoints
      breakpoints = 100 + difference
      winner = false
      winner = true if playerPoints > opponentPoints
      modifiedWin = false
      modifiedWin = true if difference < 12
      draw = false
      draw = true if difference == 0
      return [difference,breakpoints,winner,modifiedWin,draw]
    end
    
    def pointsValues
      if !self.points1.nil? and self.points1 < 0
        errors.add(:points1, I18n.t('valueZero'))
      end
      if !self.points2.nil? and self.points2 < 0
        errors.add(:points2, I18n.t('valueZero'))
      end
    end
    
    def playersAreDifferent
      return if self.player1.nil?
      return if self.player2.nil?
      if self.player1 == self.player2 
        errors.add(:player2, I18n.t('playersDifferent'))
      end
    end
    
    # def AddSOSToRankings(sos, rankings)
    #   rankings.each { |ranking|
    #     ranking.sos += sos
    #     ranking.save
    #   }
    # end
    #
    # def opponentsOfPlayerInTourney(player,tourney)
    #   playerMatches = tourney.matches.where(:player1 => player)
    #   opponents = []
    #   playerMatches.each {|match|
    #     unless match.player2.nil?
    #        ranking = Ranking.find_by(player_id: match.player2, tourney_id: tourney)
    #        opponents << ranking
    #     end
    #   }
    #
    #   playerMatches = tourney.matches.where(:player2 => player)
    #   playerMatches.each {|match|
    #     unless match.player1.nil?
    #       ranking = Ranking.find_by(player_id: match.player1, tourney_id: tourney)
    #       opponents << ranking
    #     end
    #   }
    #   return opponents
    # end
    #
    # def removeSOSforOpponentsOfPlayer(player,earned)
    #   opponents = opponentsOfPlayerInTourney(player,self.round.tourney)
    #   AddSOSToRankings(-earned,opponents)
    # end
    #
    # def addSOSforOpponentsOfPlayer(player,earned)
    #   opponents = opponentsOfPlayerInTourney(player,self.round.tourney)
    #   AddSOSToRankings(earned,opponents)
    # end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_parents, :setTab
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = @round.matches
    @selectedRound = @round
    render "rounds/index"
  end
  
  # GET /matches/new
  def new
    @match = @round.matches.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = @round.matches.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to tourney_round_matches_path(@tourney, @round), notice: t('matchCreated') }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @math = @round.matches.find(params[:id])

    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to tourney_round_matches_path(@tourney, @round), notice: t('matchUpdated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = @round.matches.find(params[:id])
    @match.destroy
    respond_to do |format|
      format.html { redirect_to tourney_round_matches_path(@tourney, @round) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    def setTab
      setActiveTab(:rounds)
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:player1_id, :player2_id, :points1, :points2, :round_id)
    end

    def load_parents
      @tourney = current_user.tourneys.find(params[:tourney_id]) 
      @round = @tourney.rounds.find(params[:round_id])
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
  
  def collectPlayersForTournmanet(tourney)
    tourney.players.order("firstName ASC, lastName ASC").collect {|p| [ p.completeName, p.id ] }
  end
  
  def collectResults
    Match.possibleResults
  end
end

app/views/matches/_form.html.erb
<%= form_for([@tourney, @round, @match], role: "form") do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row">
  <div class="col-xs-6">
	  <div class="from-group">
	    <%= f.label :player1_id %><br>
		<%= select("match", "player1_id", collectPlayersForTournmanet(@tourney), {include_blank: 'None'}, class: "form-control") %>
		</div>
  </div>
  <div class="col-xs-3">
	  <div class="form-group">
	    <%= f.label :points1 %><br>
		<%= f.number_field :points1, class: "form-control" %>
	  </div>
  </div>
</div>


<div class="row">
  <div class="col-xs-6">
	  <div class="form-group">
	    <%= f.label :player2_id %><br>
		<%= select("match", "player2_id", collectPlayersForTournmanet(@tourney), {include_blank: 'None'}, class: "form-control") %>
	  </div>
  </div>
  <div class="col-xs-3">
	  <div class="form-group">
	    <%= f.label :points2 %><br>
		<%= f.number_field :points2, class: "form-control" %>
	  </div>
  </div>
</div>


  
  
  <%= f.hidden_field :round_id, class: "form-control" %>
  
  <%= f.submit class: "btn btn-default" %>
	
<% end %>
	
	

app/views/matches/_index.html.erb
<%= link_to link_to I18n.t('newMatch'), new_tourney_round_match_path(@tourney, @selectedRound), class: "btn btn-primary btn-lg pull-right", role:"button"  unless @selectedRound.nil? %>

<% i = 0 %>
<h1><%= t('listingMatches') %> - <%= t('round') + " " + @selectedRound.order.to_s unless @selectedRound.nil? %></h1>
<%= link_to t('printPage'), tourney_round_printRound_path(@tourney, @selectedRound), class: "btn btn-info btn-lg pull-left", role:"button", :target => "_blank" unless @selectedRound.nil? %>

<%= link_to I18n.t('destroy_round'), [@tourney, @selectedRound], method: :delete, data: { confirm: t("areYouSure") }, class: "btn btn-danger btn-lg", role:"button" unless @selectedRound.nil? %>


<table class="table table-hover table-striped">
  <thead>
    <tr>
	  <th><%= I18n.t('table') %></th>
      <th><%= Match.human_attribute_name(:player1_id) %></th>
      <th><%= Match.human_attribute_name(:points1) %></th>
      <th><%= Match.human_attribute_name(:player2_id) %></th>
      <th><%= Match.human_attribute_name(:points2) %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
		<% @matches ||= [] %>
    <% @matches.each do |match| %>
      <tr>
		<td><%= i+= 1 %></td>
        <td><%= match.player1.completeName %></td>
        <td><%= match.points1 %></td>
        <td><%= match.player2.completeName unless match.player2.nil? %></td>
        <td><%= match.points2 unless match.player2.nil? %></td>
        <td><%= link_to I18n.t('edit'), edit_tourney_round_match_path(@tourney, @selectedRound, match), class: "btn btn-default btn-xs", role:"button" %></td>
        <td><%= link_to I18n.t('destroy'), [@tourney, @selectedRound, match], method: :delete, data: { confirm: t("areYouSure") }, class: "btn btn-danger btn-xs", role:"button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to link_to I18n.t('newMatch'), new_tourney_round_match_path(@tourney, @selectedRound), class: "btn btn-primary btn-lg pull-right", role:"button" unless @selectedRound.nil? %>

app/views/matches/edit.html.erb
<%= render 'form' %>

<%= link_to I18n.t('back'), tourney_round_matches_path(@tourney, @round) %>

app/views/matches/index.html.erb
<%= render 'tourneys/info' %>

<p>
  <strong><%= t('Round') %>:</strong>
  <%= @round.order %>
</p>

<h1><%= t('listingMatches') %></h1>

<%= link_to I18n.t('edit'), edit_tourney_round_path(@tourney,@round) %> |
<%= link_to I18n.t('back'), tourney_rounds_path(@tourney) %>

<table class="table">
  <thead>
    <tr>
      <th><%= Match.human_attribute_name(:player1_id) %></th>
      <th><%= Match.human_attribute_name(:points1) %></th>
      <th><%= Match.human_attribute_name(:player2_id) %></th>
      <th><%= Match.human_attribute_name(:points2) %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.player1.completeName %></td>
        <td><%= match.points1 %></td>
        <td><%= match.player2.completeName unless match.player2.nil? %></td>
        <td><%= match.points2 unless match.player2.nil? %></td>
        <td><%= link_to I18n.t('edit'), edit_tourney_round_match_path(@tourney, @round, match), class: "btn btn-default btn-xs", role:"button" %></td>
        <td><%= link_to I18n.t('destroy'), [@tourney, @round, match], method: :delete, data: { confirm: t("areYouSure") }, class: "btn btn-danger btn-xs", role:"button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to link_to I18n.t('newMatch'), new_tourney_round_match_path(@tourney, @round), class: "btn btn-primary btn-lg", role:"button" %>

app/views/matches/new.html.erb
<h1><%= t('newMatch')%></h1>

<%= render 'form' %>

<%= link_to I18n.t('back'), tourney_round_matches_path(@tourney, @round) %>